version: "3.8"
services:
  postgres:
    container_name: 'freelance_database'
    image: postgres:14.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./scripts/SQL/create-schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=test
    container_name: 'freelance_admin_panel'
    ports:
      - 5055:80
  redis:
    image: redis:alpine
    container_name: 'freelance_redis'
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
